name: mirror

on:
  push:
    branches:
      - "master"

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Git
        run: |
          git config --global user.name "${{ secrets.USER_NAME }}"
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          git config --global push.default simple
          git add .
          git commit -m “Mirror”
          git remote add Bitbucket https://${{ secrets.USER_NAME }}:${{ secrets.TOKEN }}@bitbucket.org/wynntils/reference
          git fetch --unshallow
          git push -f Bitbucket master
